version: '3'

services:
  app:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    environment:
      - DB_HOST=db
      - DB_DATABASE=crater
      - DB_USERNAME=crater
      - DB_PASSWORD=crater_pass
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater_pass
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater_root_pass
    volumes:
      - ./db_data:/var/lib/mysql

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crater.rule=Host(`crater.nordikforge.com`)"
      - "traefik.http.routers.crater.entrypoints=websecure"
      - "traefik.http.routers.crater.tls.certresolver=myresolver"
      - "traefik.http.services.crater.loadbalancer.server.port=80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - app

  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - app

networks:
  default:
    name: web_network
    external: true
